### ISSUE TITLE
Texte automatisiert einfügen

### ISSUE THREAD

**Issue by fhp-campusambulanz** [Campusambulanz/ca-website#10]
Texte (mittels gulp Modul?) automatisiert einfügen, so dass auch "Nicht-HTML-Kenner" problemlos in der Lage sind, einzelne Texte auszutauschen (bspw. Termine im nächsten Jahr).

Bedenke:
- gulp Modul muss im gulpfile eingebunden werden
- an welchen Stellen macht es Sinn? (eventuell gibt es auch allgemeine statische Texte)

**Comment by topada** [comment]
Ich schlage vor sämtliches HTML mittels JADE einzubinden. Jade ist ein Proprocessor für HTML vergleichbar mit LESS zu CSS. So können wir alle Variablen in eine Datei auslagern. Außerdem ist die Syntax so reduziert, dass sie auch von Nicht-HTMLern sehr leicht verstanden werden kann. Für Jade gibt es ein Gulp Module, sodass wir keine weitere Arbeit damit haben werden. Ich starte ein Branch –

**Comment by topada** [comment]
oh ich sehe gerade wir nutzen ja schon nunjucks! damit lässt sich das natürlich auch realisieren :)

**Comment by topada** [comment]
Ich habe jetzt alles HTML in JADE gezogen – neu entstanden ist das File ADMIN.JADE; schau mal rein :)
https://github.com/Campusambulanz/ca-website/tree/dynamic-content-migrate-nunjucks-to-jade

**Comment by dnsos** [comment]
Mit #25 haben wir das gelöst. Variabler Content kann von nun an in der admin.jade bearbeitet werden.
