### ISSUE TITLE
Accordion mit js umsetzen?

### ISSUE THREAD

**Issue by fhp-campusambulanz** [Campusambulanz/ca-website#11]
Aktuell noch per CSS umgesetzt. Macht es Sinn, das zu ändern?

Vorteile:
- smoother Übergang
- keine Sprünge bei Auswählen

Nachteile:
- wenn js deaktiviert, entweder nicht aufklappbar oder ALLEs aufgeklappt und somit extrem lang

**Comment by topada** [comment]
Ich denke die JS Variante sollte klar gehen – deaktiviertes JS ist, zumindest in der Zielgruppe, eher geringverschwindend. #pechgehabt!

**Comment by topada** [comment]
checkout smooth-accordion branch  f40a451

**Comment by topada** [comment]
bug: background svgs jump, possible fix with css > background-positioning

@dnsos check mal, ob das okay ist (section mappe); dann ändere ich die jade files für alle accordions

**Comment by dnsos** [comment]
Jo, passt.

**Comment by topada** [comment]
fixed in  af84523, ready to merge #32.
