### ISSUE TITLE
.gitignore file 

### ISSUE THREAD

**Issue by topada** [Campusambulanz/ca-website#12]
Läuft das mit der gitignore bei euch?

bei mir will er immer wieder aus dem build-folder naschen; hoffe das lässt sich beheben :)

**Comment by fhp-campusambulanz** [comment]
Bei mir funktioniert's leider auch nicht. Aber ist ja zum Glück erstmal nicht das ganz große Problem.

**Comment by topada** [comment]
jetzt klappts! wenn etwas aus dem build-ordner nochmal bei dir im github auftauchen sollte, liegt es am cache.
1. alle commits updaten
2. im terminal "git rm -r --cached build" eingeben
3. commit und fertig!

jetzt sollte der build ordner wirklich ignoriert werden ;-)

**Comment by fhp-campusambulanz** [comment]
... Hmm, jetzt ist aber leider der build-Ordner komplett bei mir verschwunden. Ich denke, das liegt daran, dass er nicht mehr im Github ist und das dann synchronisiert wird... Bei dir lokal existiert der aber noch?

Sonst müssen wir das vielleicht doch nochmal ändern...
