### ISSUE TITLE
Schlafplatz-Suche Tool einbauen

### ISSUE THREAD

**Issue by dnsos** [Campusambulanz/ca-website#16]
Muss das mit PHP oder kann man das auch anders hinbekommen?

**Comment by topada** [comment]
und neues deaktivieren

**Comment by topada** [comment]
javascript selbst bietet keine Möglichkeit E-Mails zu versenden, so wie wir es bisher mit der PHP Version gewohnt waren. Ich würde gerne diskutieren, ob ein E-Mail Formular überhaupt noch zeitgemaß ist? Gerade auf dem Smartphone kann es eher nerven ein Fremd-Formular zu befüllen als einfach in die dafür **gemacht** und **gewohnte** E-Mail App zu linken. Was sagt ihr?

**Comment by dnsos** [comment]
Stimme ich 100% zu.

**Comment by donatuswolf** [comment]
also statt Formular einfach die mail-adresse rein schreiben?
