### ISSUE TITLE
Doku anlegen

### ISSUE THREAD

**Issue by dnsos** [Campusambulanz/ca-website#23]
In der README.md

**Comment by topada** [comment]
i'm on it! bin von morgen bis sonntag allerdings in instanbul und werde erst danach weitermachen! Wir bekommen das Ding aber jetzt sicher fertig!

https://github.com/Campusambulanz/ca-website/tree/clean-readme

**Comment by topada** [comment]
update update! bitte checkt mal wieder

https://github.com/Campusambulanz/ca-website/tree/clean-readme

Ja nein vielleicht?

**Comment by topada** [comment]
closed
