### ISSUE TITLE
Rakete während des Ladevorgangs fehlt

### ISSUE THREAD

**Issue by dnsos** [Campusambulanz/ca-website#37]
@topada kannst du das nochmal prüfen?

Die Bilder "rocket_load.jpg" und "ajax-loader.gif" können nicht geladen werden und sind auch nirgendwo im src-Ordner zu finden. Eventuell irgendwie lokal hängen gelieben?

**Comment by topada** [comment]
Very much so! 🙋🏻‍♂️😬😂 ich fixe das!

**Comment by topada** [comment]
fixed #d95755b
