### ISSUE TITLE
Rocket Animation in Firefox

### ISSUE THREAD

**Issue by fhp-campusambulanz** [Campusambulanz/ca-website#4]
CSS3-Animation der Rocket ist im Firefox fehlerhaft (vertikale Verzerrung)

**Comment by dnsos** [comment]
Okay, ich kann leider echt nicht nachvollziehen, warum dieser Bug auftaucht. Wenn ihr was rausfindet - gerne.

Ansonsten würde ich sagen, dass es erstmal nicht so dramatisch ist und uns nicht davon abhält, die Seite fertig zu stellen und online zu stellen.

**Comment by topada** [comment]
tritt der fehler immernoch auf? welche firefox version nutzt du?

**Comment by dnsos** [comment]
Leider ja. Ich habe immer die neueste getestet, zuletzt 50.0

Hast du den Fehler denn nicht?

**Comment by topada** [comment]
böse zungen sagen ja, dass die installation von firefox schon eine Grundproblematik darstellt – nagut ich installiere und schaue! 💃
