### ISSUE TITLE
Übergang von Mappe zu Anfahrt (Chrome)

### ISSUE THREAD

**Issue by fhp-campusambulanz** [Campusambulanz/ca-website#5]
Zwischen den Sections erscheint in Chrome ein "Blitzer" am unteren Rand des PNGs, das die Sections trennt.

**Comment by topada** [comment]
betrifft wohl alle -webkit browser. eine workaround idee wäre mit max-height / max-width zu arbeiten
https://bugs.webkit.org/show_bug.cgi?id=82489

ansonsten könnte ich mir auch eine lösung mittels background-img und background-size: cover; vorstellen

**Comment by topada** [comment]
Der Grund für die Blitzer ist das Rendering der SVGs in half pixels, abhängig von der Breite des Browsers. Ich habe gerade einen Test mit dem shape-rendering tag innerhalb der svg datei. Leider konnte ich auch damit kein zufriedenstellendes ergebnis erzielen.

[mozilla.org svg shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering)

**Comment by topada** [comment]
suggesting close for now

**Comment by dnsos** [comment]
Yo!
